name: Simple Pipeline on push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.6'
          mysql database: 'database'
          mysql root password: root

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install composer
        uses: php-actions/composer@v6

      - name: Remove vendor
        run: sudo rm -rf vendor

      - name: Install project dependencies
        run: sudo composer install

      - name: Run PHP STAN
        run: vendor/bin/phpstan analyse app/Http/Helpers/ app/Http/Services/ tests/ --level 5

      - name: Run PHPMD
        run: vendor/bin/phpmd ./app/Http/ github codesize,controversial,design,naming,unusedcode --exclude 'vendor/*'

      - name: Rename .env.example
        run: mv .env.example .env

      - name: Generate Laravel key
        run: php artisan key:generate

      - name: Install Laravel Migrate
        run: php artisan migrate:install

      - name: Run Laravel Migrate
        run: php artisan migrate

      - name: Run PHP Unit
        run: vendor/bin/phpunit
